import 'package:flutter/material.dart';
import 'package:fonde_ui/fonde_ui.dart';
import 'package:fonde_ui/fonde_ui_riverpod.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../widgets/catalog_page.dart';

class PlatformMenusPage extends StatelessWidget {
  const PlatformMenusPage({super.key});

  @override
  Widget build(BuildContext context) {
    return CatalogPage(
      children: [
        CatalogSection(
          title: 'FondePlatformMenus',
          description:
              'Platform menu bar (macOS/Windows) utilities. '
              'This catalog app itself uses FondePlatformMenus — check the menu bar above.',
          children: [
            const _MenuBarNotice(),
            const FondeSpacing.lg(),
            const _CodeSample(),
          ],
        ),
      ],
    );
  }
}

class _MenuBarNotice extends ConsumerWidget {
  const _MenuBarNotice();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final colorScheme = ref.watch(fondeEffectiveColorSchemeProvider);
    return Container(
      decoration: BoxDecoration(
        color: colorScheme.uiAreas.sideBar.background,
        borderRadius: FondeBorderRadiusValues.mediumRadius,
        border: Border.all(color: colorScheme.base.divider),
      ),
      padding: const EdgeInsets.all(FondeSpacingValues.lg),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(
            Icons.info_outline,
            size: 16,
            color: colorScheme.base.foreground.withValues(alpha: 0.55),
          ),
          const SizedBox(width: FondeSpacingValues.sm),
          Expanded(
            child: FondeText(
              'This catalog app registers a platform menu bar using '
              'FondePlatformMenus. On macOS, open the menu bar and explore '
              'the App, Edit, File, View, and Window menus to see the items '
              'generated by this utility.',
              variant: FondeTextVariant.bodyText,
              color: colorScheme.base.foreground.withValues(alpha: 0.75),
            ),
          ),
        ],
      ),
    );
  }
}

class _CodeSample extends ConsumerWidget {
  const _CodeSample();

  static const _code = r'''
// Create an instance using the current BuildContext.
final menus = FondePlatformMenus(context: context);

// Use in PlatformMenuBar.
PlatformMenuBar(
  menus: [
    // App menu (macOS application menu with Services, Hide, Quit, etc.)
    menus.appMenu(
      appName: 'My App',
      onAbout: () => showAboutDialog(context),
      onPreferences: () => showPreferencesDialog(context),
    ),

    // File menu — mix utility items with custom ones
    PlatformMenu(
      label: 'File',
      menus: [
        PlatformMenuItem(label: 'New...', onSelected: _onNew),
        PlatformMenuItemGroup(
          members: menus.fileSaveItems(onSave: _onSave),
        ),
        PlatformMenuItemGroup(
          members: menus.filePrintItems(onPrint: _onPrint),
        ),
      ],
    ),

    // Edit menu — standard groups with callbacks
    PlatformMenu(
      label: 'Edit',
      menus: [
        PlatformMenuItemGroup(
          members: menus.editUndoItems(onUndo: _onUndo, onRedo: _onRedo),
        ),
        PlatformMenuItemGroup(
          members: menus.editClipboardItems(),
        ),
        PlatformMenuItemGroup(
          members: menus.editFindItems(onFind: _onFind),
        ),
      ],
    ),

    // View menu
    PlatformMenu(
      label: 'View',
      menus: [
        PlatformMenuItemGroup(
          members: menus.viewZoomItems(
            onZoomIn: _onZoomIn,
            onZoomOut: _onZoomOut,
            onActualSize: _onActualSize,
          ),
        ),
        PlatformMenuItemGroup(
          members: menus.viewFullScreenItems(),
        ),
      ],
    ),

    // Window menu (Minimize, Zoom, Bring All to Front)
    menus.windowMenu(),
  ],
  child: myApp,
);''';

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final colorScheme = ref.watch(fondeEffectiveColorSchemeProvider);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        FondeText(
          'Sample Code',
          variant: FondeTextVariant.sectionTitleSecondary,
          color: colorScheme.base.foreground.withValues(alpha: 0.55),
        ),
        const FondeSpacing.sm(),
        Container(
          width: double.infinity,
          decoration: BoxDecoration(
            color: colorScheme.uiAreas.sideBar.background,
            borderRadius: FondeBorderRadiusValues.mediumRadius,
            border: Border.all(color: colorScheme.base.divider),
          ),
          padding: const EdgeInsets.all(FondeSpacingValues.lg),
          child: SelectableText(
            _code,
            style: const TextStyle(
              fontFamily: 'monospace',
              fontSize: 12,
              height: 1.6,
            ),
          ),
        ),
      ],
    );
  }
}
